/****************************************************************************
 * DoomMake Build Script
 *
 * DoomMake employs a language called RookScript.
 * Documentation is included for this in the DoomTools docs folder.
 * All WadScript and DoomMake extensions are available here. 
 ****************************************************************************/

#include "scripts/doommake-lib.script"
#include "scripts/doommake-init.script"

/* ------------------------------------------------------------------------ */

function listUncleanedFiles(dir) {
	each (f : filelist(file(dir), true)) {
		printerrln("* " + filepath(f));
	}
}

/**
 * Cleans the build directory and distro directory found in the properties.
 */
function doClean() {
	initBuild();
	println("Cleaning build and dist...");
	out = cleandir(getBuildDirectory()) && cleandir(getDistDirectory());	
	println("Done.");
	if (!out) {
	    printerrln("ERROR: Clean failed - the following files were not deleted:");
	    listUncleanedFiles(getBuildDirectory());
	    listUncleanedFiles(getDistDirectory());
	}
		
	return out; 
}


/* ------------------------------------------------------------------------ */

/**
 * Builds the editor assets WAD file in the build directory.
 */
function doEditorAssets() {

	editorWad = getBuildDirectory() + "/" + getEditorWAD();

	if (checkFileExistenceAndBuildStatuses(editorWad, ["dehacked", "assets", "textures"])) {
		println("[Skipped] Assets, textures, and DeHackEd patches were not built. Skipping editor WAD rebuild.");
		return;
	}
	
	mergeEditorAssets(editorWad);

	setBuilt("editor");
}


