/****************************************************************************
 * DoomMake Project Init Script
 ****************************************************************************/

/**
 * Performs project initialization.
 * Usually used for downloading dependencies or other setup.
 */
function doInit(args) {

	// ---------------------------------------------------
	// If this project needs initial setup, do it here.
	// ---------------------------------------------------

}
