/**
 * Merges a set of WADs together into one.
 *
 * outputWadFile: the output WAD file path.
 * wadList: a list of WAD files.
 */
function mergeWads(outputWadFile, wadList) {
	check (err) {
		destwad = wadfilecreate(outputWadFile);
		each (w : wadList) {
			check (err) {
				srcwad = wadfile(w);
				println("Merging map " + w + "...");
				destWad->wadimport(srcwad, srcwad->wadentries());
			}
			close(srcwad);
			if (err)
				return err;
		}
	}
	close(destwad);
	if (err)
		return err;
}

