/*****************************************************************************
 * TARGET: converttextures
 *****************************************************************************
 * Converts texture flats and patches to Doom formats and puts them in the 
 * texture directories.
 * doommake converttextures
 ****************************************************************************/
check entry converttextures(args) {
	doConvertFlats();
	doConvertPatches();
	doConvertTextures();
}


