/*****************************************************************************
 * TARGET: assets
 *****************************************************************************
 * Converts and merges the assets WAD.
 * doommake assets
 ****************************************************************************/
check entry assets(args) {
	doConvertSounds();
	doConvertGraphics();
	doConvertSprites();
	doConvertColormaps();
	doAssets();
}


