/*****************************************************************************
 * TARGET: maptextures
 *****************************************************************************
 * Reads the map WADs and texture resources and exports them to a WAD 
 * of used textures.
 * doommake maptextures
 ****************************************************************************/
check entry mapTextures(args) {
	doMapTextures();
}

