/*******************************************************************************
 * Copyright (c) 2020-2021 Matt Tropiano
 * This program and the accompanying materials are made available under 
 * the terms of the MIT License, which accompanies this distribution.
 ******************************************************************************/
package net.mtrop.doom.tools.decohack.patches;

import static net.mtrop.doom.tools.decohack.data.DEHActionPointer.*;

import net.mtrop.doom.tools.decohack.data.DEHState;
import net.mtrop.doom.tools.decohack.data.DEHThing;

/**
 * Constants for MBF. 
 * @author Matthew Tropiano
 */
interface ConstantsExtended 
{
	static final PatchBoom.State[] DEHSTATEEXTENDED = 
	{
		PatchBoom.State.create(DEHState.create(58, 0, false, 806, 6), NULL),
		PatchBoom.State.create(DEHState.create(144, 0, false, 0, -1), NULL),
		PatchBoom.State.create(DEHState.create(144, 1, false, 0, -1), NULL),
		PatchBoom.State.create(DEHState.create(144, 2, false, 0, -1), NULL),
		PatchBoom.State.create(DEHState.create(144, 3, false, 0, -1), NULL),
		PatchBoom.State.create(DEHState.create(144, 4, false, 0, -1), NULL),
		PatchBoom.State.create(DEHState.create(144, 5, false, 0, -1), NULL),
		PatchBoom.State.create(DEHState.create(144, 6, false, 0, -1), NULL),
		PatchBoom.State.create(DEHState.create(144, 7, false, 0, -1), NULL),
		PatchBoom.State.create(DEHState.create(17, 0, true, 1086, 4), NULL),
		PatchBoom.State.create(DEHState.create(17, 1, false, 1087, 4), NULL),
		PatchBoom.State.create(DEHState.create(17, 2, false, 1088, 10), NULL),
		PatchBoom.State.create(DEHState.create(17, 3, false, 0, 14), NULL),
	};
	
	public static final DEHThing[] DEHTHINGEXTENDED = 
	{
		(new DEHThing()).setName("Music Source"),
		(new DEHThing()).setName("MT_GIBDTH"),
		(new DEHThing()).setName("MT_BLUEBLOOD"),
		(new DEHThing()).setName("MT_GREENBLOOD"),
		(new DEHThing()).setName("MT_FUZZYBLOOD"),
		(new DEHThing()).setName("MT_TRAIL"),
		(new DEHThing()).setName("Extra thing 0"),
		(new DEHThing()).setName("Extra thing 1"),
		(new DEHThing()).setName("Extra thing 2"),
		(new DEHThing()).setName("Extra thing 3"),
		(new DEHThing()).setName("Extra thing 4"),
		(new DEHThing()).setName("Extra thing 5"),
		(new DEHThing()).setName("Extra thing 6"),
		(new DEHThing()).setName("Extra thing 7"),
		(new DEHThing()).setName("Extra thing 8"),
		(new DEHThing()).setName("Extra thing 9"),
		(new DEHThing()).setName("Extra thing 10"),
		(new DEHThing()).setName("Extra thing 11"),
		(new DEHThing()).setName("Extra thing 12"),
		(new DEHThing()).setName("Extra thing 13"),
		(new DEHThing()).setName("Extra thing 14"),
		(new DEHThing()).setName("Extra thing 15"),
		(new DEHThing()).setName("Extra thing 16"),
		(new DEHThing()).setName("Extra thing 17"),
		(new DEHThing()).setName("Extra thing 18"),
		(new DEHThing()).setName("Extra thing 19"),
		(new DEHThing()).setName("Extra thing 20"),
		(new DEHThing()).setName("Extra thing 21"),
		(new DEHThing()).setName("Extra thing 22"),
		(new DEHThing()).setName("Extra thing 23"),
		(new DEHThing()).setName("Extra thing 24"),
		(new DEHThing()).setName("Extra thing 25"),
		(new DEHThing()).setName("Extra thing 26"),
		(new DEHThing()).setName("Extra thing 27"),
		(new DEHThing()).setName("Extra thing 28"),
		(new DEHThing()).setName("Extra thing 29"),
		(new DEHThing()).setName("Extra thing 30"),
		(new DEHThing()).setName("Extra thing 31"),
		(new DEHThing()).setName("Extra thing 32"),
		(new DEHThing()).setName("Extra thing 33"),
		(new DEHThing()).setName("Extra thing 34"),
		(new DEHThing()).setName("Extra thing 35"),
		(new DEHThing()).setName("Extra thing 36"),
		(new DEHThing()).setName("Extra thing 37"),
		(new DEHThing()).setName("Extra thing 38"),
		(new DEHThing()).setName("Extra thing 39"),
		(new DEHThing()).setName("Extra thing 40"),
		(new DEHThing()).setName("Extra thing 41"),
		(new DEHThing()).setName("Extra thing 42"),
		(new DEHThing()).setName("Extra thing 43"),
		(new DEHThing()).setName("Extra thing 44"),
		(new DEHThing()).setName("Extra thing 45"),
		(new DEHThing()).setName("Extra thing 46"),
		(new DEHThing()).setName("Extra thing 47"),
		(new DEHThing()).setName("Extra thing 48"),
		(new DEHThing()).setName("Extra thing 49"),
		(new DEHThing()).setName("Extra thing 50"),
		(new DEHThing()).setName("Extra thing 51"),
		(new DEHThing()).setName("Extra thing 52"),
		(new DEHThing()).setName("Extra thing 53"),
		(new DEHThing()).setName("Extra thing 54"),
		(new DEHThing()).setName("Extra thing 55"),
		(new DEHThing()).setName("Extra thing 56"),
		(new DEHThing()).setName("Extra thing 57"),
		(new DEHThing()).setName("Extra thing 58"),
		(new DEHThing()).setName("Extra thing 59"),
		(new DEHThing()).setName("Extra thing 60"),
		(new DEHThing()).setName("Extra thing 61"),
		(new DEHThing()).setName("Extra thing 62"),
		(new DEHThing()).setName("Extra thing 63"),
		(new DEHThing()).setName("Extra thing 64"),
		(new DEHThing()).setName("Extra thing 65"),
		(new DEHThing()).setName("Extra thing 66"),
		(new DEHThing()).setName("Extra thing 67"),
		(new DEHThing()).setName("Extra thing 68"),
		(new DEHThing()).setName("Extra thing 69"),
		(new DEHThing()).setName("Extra thing 70"),
		(new DEHThing()).setName("Extra thing 71"),
		(new DEHThing()).setName("Extra thing 72"),
		(new DEHThing()).setName("Extra thing 73"),
		(new DEHThing()).setName("Extra thing 74"),
		(new DEHThing()).setName("Extra thing 75"),
		(new DEHThing()).setName("Extra thing 76"),
		(new DEHThing()).setName("Extra thing 77"),
		(new DEHThing()).setName("Extra thing 78"),
		(new DEHThing()).setName("Extra thing 79"),
		(new DEHThing()).setName("Extra thing 80"),
		(new DEHThing()).setName("Extra thing 81"),
		(new DEHThing()).setName("Extra thing 82"),
		(new DEHThing()).setName("Extra thing 83"),
		(new DEHThing()).setName("Extra thing 84"),
		(new DEHThing()).setName("Extra thing 85"),
		(new DEHThing()).setName("Extra thing 86"),
		(new DEHThing()).setName("Extra thing 87"),
		(new DEHThing()).setName("Extra thing 88"),
		(new DEHThing()).setName("Extra thing 89"),
		(new DEHThing()).setName("Extra thing 90"),
		(new DEHThing()).setName("Extra thing 91"),
		(new DEHThing()).setName("Extra thing 92"),
		(new DEHThing()).setName("Extra thing 93"),
		(new DEHThing()).setName("Extra thing 94"),
		(new DEHThing()).setName("Extra thing 95"),
		(new DEHThing()).setName("Extra thing 96"),
		(new DEHThing()).setName("Extra thing 97"),
		(new DEHThing()).setName("Extra thing 98"),
		(new DEHThing()).setName("Extra thing 99"),
	};
	
}
